---
layout: archive
title: "📑Publications"
permalink: /selected-publications/
author_profile: true
---

**Journal Articles** (\* Corresponding author)
======

1. **J. Jin**, W. Wang\*, W. Jiao, M. Sun, H. Xu, and C. Tian. "Seismic performance of an unequal-depth steel beam-to-CFST column joint with insert diaphragm: Experiment, numerical analysis and design method." *Thin-Walled Structures*, 222 (2026), 114508. (SCI, Q1, Top, IF: 8.3) [DOI](https://doi.org/10.1016/j.tws.2026.114508)
2. **J. Jin**, W. Wang\*, M. Sun, W. Jiao, and H. Xu. "Experimental, numerical, and theoretical investigations on cyclic performance of staggered-floor steel beam-to-CFST column connections with partially insert-diaphragms." *Journal of Building Engineering*, 128 (2026), 116686. (SCI, Q1, Top, IF: 8.1) [DOI](https://doi.org/10.1016/j.jobe.2026.116686)
3. P. Li, **J. Jin**\*, Y. Sheng, W. Wang, W. Jiao, and T. Gou. "Numerical study and design method of irregular steel beam-to-CFST column joints with inclined internal diaphragms." *Buildings*, 16 (2026), 1502. (SCI, Q2, IF: 3.4) [DOI](https://doi.org/10.3390/buildings16081502)
4. **J. Jin**, T. Yan, T. Nagae, W. Wang\*, and M. Sun. "Seismic repair assessment of welded beam-to-box column connections in high-rise steel buildings." *Journal of Constructional Steel Research*, 235 (2025), 109836. (SCI, Q1, IF: 4.6) [DOI](https://doi.org/10.1016/j.jcsr.2025.109836)
5. **J. Jin**, T. Yan, T. Nagae\*, Y.L. Chung, and L.F. Ibarra. "Seismic retrofit of H-section beam-to-HSS column connections in existing high-rise steel buildings." *Journal of Building Engineering*, 111 (2025), 113432. (SCI, Q1, Top, IF: 8.1) [DOI](https://doi.org/10.1016/j.jobe.2025.113432)
6. P. Li, **J. Jin**\*, C. Shi, W. Wang, and W. Jiao. "Experimental study on seismic behavior of irregular-shaped steel beam-to-CFST column joints with inclined internal diaphragms." *Buildings*, 15 (2025), 4514. (SCI, Q2, IF: 3.4) [DOI](https://doi.org/10.3390/buildings15244514)
7. **J. Jin**, T. Nagae\*, T. Asai, T. Okazaki, J. Li, D.G. Lignos, Y.L. Chung, J. Fujiwara, A. Kishida, and K. Kajiwara. "Cyclic pushover analysis for seismic response evaluation of a full-scale 10-story steel building tested on the E-Defense shake-table." *Journal of Building Engineering*, 96 (2024), 110552. (SCI, Q1, Top, IF: 8.1) [DOI](https://doi.org/10.1016/j.jobe.2024.110552)
8. **J. Jin**, T. Yan, T. Nagae\*, T. Okazaki\*, T. Matsumiya, and N. Takahashi. "Effect of composite slab and connection detail on cyclic behavior of steel beam-to-HSS column moment connections." *Journal of Building Engineering*, 95 (2024), 110254. (SCI, Q1, Top, IF: 8.1) [DOI](https://doi.org/10.1016/j.jobe.2024.110254)
9. **J. Jin**, Y.L. Chung\*, T. Nagae\*, T. Yan, E. Shigeta, and K.C. Lin. "Post-earthquake repair of welded unreinforced flange-bolted web connections considering composite slab effects." *Journal of Constructional Steel Research*, 221 (2024), 108911. (SCI, Q1, IF: 4.6) [DOI](https://doi.org/10.1016/j.jcsr.2024.108911)
10. **J. Jin**, X. Qian, P.S. Chen, and B. Liu\*. "Recommendations to structural design of 1.5-layer space frames with crossing-units and triple-connecting units based on buckling features." *Structures*, 70 (2024), 107877. (SCI, Q1, IF: 4.9) [DOI](https://doi.org/10.1016/j.istruc.2024.107877)
11. **J. Jin**\*, T. Nagae\*, and Y.L. Chung. "Seismic and collapse behavior of existing high-rise steel buildings under long-period earthquakes." *Journal of Constructional Steel Research*, 211 (2023), 108151. (SCI, Q1, IF: 4.6) [DOI](https://doi.org/10.1016/j.jcsr.2023.108151)
12. **J. Jin**, X. Qian, and P.S. Chen\*. "Study on buckling characteristics of cylindrical and domed 1.5-layer space frames with lap-units." *Journal of Structural Engineering B, AIJ*, 67B (2021), 251-260. (High-quality Japanese journal) [Paper](https://www.aij.or.jp/paper/detail.html?productId=655654)
13. J. Fujiwara\*, **J. Jin**, J. Li, T. Yan, R. Nishi, A. Kishida, K. Kajiwara, T. Nagae\*, T. Okazaki, and T. Asai. "Full-scale shaking table tests on a 10-story steel frame building with buckling-restrained braces." *Earthquake Engineering & Structural Dynamics* (2026), 1-23. (SCI, Q1, IF: 4.9) [DOI](https://doi.org/10.1002/eqe.70202)
14. J. Li\*, **J. Jin**, T. Yan, J. Fujiwara, K. Kajiwara, A. Kishida, R. Nishi, T. Nagae, T. Asai, and T. Okazaki. "Bidirectional loading response of column panel zones measured in shake-table tests on a 10-story steel building." *Journal of Structural Engineering, ASCE*, 151(5) (2025), 04025050. (SCI, Q1, IF: 3.8) [DOI](https://doi.org/10.1061/JSENDH.STENG-13984)
15. T. Yan, **J. Jin**, J. Li, J. Fujiwara, A. Kishida, R. Nishi, K. Takaya, K. Kajiwara, T. Asai, T. Okazaki, and T. Nagae\*. "Numerical analysis of the seismic performance of a 10-story steel building with weak panel zones based on full-scale shake-table tests." *Journal of Building Engineering*, 111 (2025), 113458. (SCI, Q1, Top, IF: 8.1) [DOI](https://doi.org/10.1016/j.jobe.2025.113458)
16. T. Yan, **J. Jin**, T. Nagae\*, and Y.L. Chung\*. "Seismic behavior of WUF-B connections repaired and strengthened using field-welded wing plates." *Journal of Constructional Steel Research*, 224 (2025), 109089. (SCI, Q1, IF: 4.6) [DOI](https://doi.org/10.1016/j.jcsr.2024.109089)
17. B. Liu, **J. Jin**, P.S. Chen, H.B. Ge, Y. Luo, and Y. Shen\*. "Global buckling evaluation equation for preliminary design of single-layer cylindrical grid shells with diagonal rod grid and piped members." *Structures*, 78 (2025), 109366. (SCI, Q1, IF: 4.9) [DOI](https://doi.org/10.1016/j.istruc.2025.109366)
18. T. Yan, Y.L. Chung\*, **J. Jin**, K.C. Lin, Y. Komatsu, and T. Nagae\*. "Full-scale tests on resilient post-earthquake repair of steel beam-to-column connections." *Journal of Building Engineering*, 108 (2025), 112845. (SCI, Q1, Top, IF: 8.1) [DOI](https://doi.org/10.1016/j.jobe.2025.112845)
19. K. Takaya, **J. Jin**, and T. Nagae\*. "Practical repair cost assessment of steel office buildings with diverse beam-to-column connection types in Japan." *Buildings*, 14(12) (2024), 3913. (SCI, Q2, IF: 3.4) [DOI](https://doi.org/10.3390/buildings14123913)
20. B. Liu, P.S. Chen\*, X. Yan, and **J. Jin**. "Fitting the approximate equation to estimate the global buckling load of cylindrical single-layer space frames." *Journal of Technology and Design, AIJ*, 29(72) (2023), 725-730. (EI) [DOI](https://doi.org/10.3130/aijt.29.725)
21. X. Yan, P.S. Chen\*, B. Liu, B.S. Mohammed, and **J. Jin**. "Effect of hollow body material on mechanical properties of bubble concrete." *Crystals*, 12(5) (2022), 708. (SCI, Q2, IF: 2.9) [DOI](https://doi.org/10.3390/cryst12050708)
22. X. Yan, P.S. Chen\*, A. Al-Fakih, B. Liu, B.S. Mohammed, and **J. Jin**. "Experiments and mechanical simulation on bubble concrete: Studies on the effects of shape and position of hollow bodies mixed in concrete." *Crystals*, 11 (2021), 858. (SCI, Q2, IF: 2.9) [DOI](https://doi.org/10.3390/cryst11080858)

**Manuscripts Under Review**
23. H. Lee, **J. Jin**\*, T. Nagae, and N. Kawashima. "Seismic performance evaluation of back-mullion curtain wall systems through full-scale testing and practical modeling framework." *Journal of Building Engineering* (2026). (Under Review)
24. **J. Jin**, W. Wang\*, M. Sun, Hui Zhou, W. Jiao, and Y. Zhang. "Experimental study and numerical simulation for the seismic performance of novel irregular steel beam-CFST column joints with concrete-anchored slip-critical blind bolts." *Thin-Walled Structures* (2026). (Under Review)
25. **J. Jin**, W. Wang\*, M. Sun, H. Xu, and W. Jiao. "Effect of local thickness enhancement on seismic performance of special-shaped steel beam-to-square CFST column joints with inclined internal diaphragms." *Structures* (2026). (Under Review)
26. **J. Jin**, W. Wang\*, M. Sun, Hui Zhou, and W. Jiao. "Seismic behavior and design of irregular steel beam-to-square CFST column joints with improved concrete-anchored slip-critical blind bolts." *Engineering Structures* (2026). (Under Review)
27. **J. Jin**, W. Wang, M. Sun\*, and W. Jiao. "Seismic performance and design method of square hollow section column-to-beam connections with slip-critical blind bolts." *Thin-Walled Structures* (2026). (Under Review)
28. Z. Wang, W. Cheng, and **J. Jin**\*. "Axial compressive behavior and load-sharing mechanism of hybrid fiber-reinforced concrete confined composite columns: Experimental and numerical investigation." *Journal of Building Engineering* (2026). (Under Review)
29. **J. Jin**, Y. Chen, S. Wang\*, and T. Yan. "Seismic performance and retrofitting of existing unequal-depth steel beam-to-HSS column connections." *Structures* (2026). (Under Review)
30. T. Yan\*, T. Nagae, T. Okazaki, M. Somarriba, **J. Jin**, and J. Li. "Frame action on collapse resistance observed in shake-table tests of a scaled 4-story steel moment-resisting frame." *Journal of Building Engineering* (2026). (Under Review)

**International Conference Proceedings (Peer-reviewed)** (◯ Presenter)
======

1. ◯ **J. Jin**, T. Nagae, T. Asai, D.G. Lignos, Y.L. Chung, T. Okazaki, J. Fujiwara, A. Kishida, and K. Kajiwara. "Static cyclic pushover analysis evaluating seismic behaviors in multi-story building system testing." EXP Experimental Testing, EXP-2, *Proceedings of the 18th World Conference on Earthquake Engineering (WCEE 2024)*, Milan, Italy, June 30-July 5, 2024. [Paper](https://cir.nii.ac.jp/crid/1010588205174105480?lang=en)
2. ◯ **J. Jin**, P.S. Chen, B. Liu, and X. Yan. "Dynamic properties and seismic performance of 1.5-layer space frames with lap-units whilst considering vibration of lower joints." *Proceedings of the AWAM International Conference on Civil Engineering (AICCE 2022)*, Vol. 2, pp. 235-254, Universiti Sains Malaysia (USM), February 2022. [DOI](https://doi.org/10.1007/978-981-99-6018-7_18)
3. J. Li, J. Fujiwara, K. Kajiwara, A. Kishida, R. Nishi, ◯ T. Okazaki, T. Nagae, **J. Jin**, and T. Asai. "Panel zone and column response in a shake-table test on a 10-story steel moment-resisting frame." CMS Concrete, Masonry, Steel, Timber Structures, CMS-6, *Proceedings of the 18th World Conference on Earthquake Engineering (WCEE 2024)*, Milan, Italy, June 30-July 5, 2024. [Paper](https://www.researchgate.net/publication/394224671_Panel_zone_and_column_response_in_a_shake-table_test_on_a_10-story_steel_moment-resisting_frame)
4. ◯ J. Fujiwara, T. Nagae, T. Yan, **J. Jin**, J. Li, T. Okazaki, A. Kishida, R. Nishi, and K. Kajiwara. "3D detailed finite element analysis of full-scale shaking table test on a 10-story steel building." EXP Experimental Testing, EXP-2, *Proceedings of the 18th World Conference on Earthquake Engineering (WCEE 2024)*, Milan, Italy, June 30-July 5, 2024. [Paper](https://www.researchgate.net/publication/394224202_3D_detailed_finite_element_analysis_of_full-scale_shaking_table_test_on_a_10-story_steel_building)
5. ◯ X. Qian, **J. Jin**, and P.S. Chen. "Buckling characteristics of key parts of 1.5-layer space frames with lap-units." *Proceedings of the IASS 2022 Symposium affiliated with the APCS 2022 Conference*, Beijing, China, September 2022. [Search](https://cir.nii.ac.jp/all?q=Buckling%20characteristics%20of%20key%20parts%20of%201.5-layer%20space%20frames%20with%20lap-units)
6. ◯ B. Liu, P.S. Chen, X. Yan, and **J. Jin**. "Approximate equation for evaluating global buckling load of single-layer cylindrical space frames with crossing pattern." *Proceedings of the IASS 2022 Symposium affiliated with the APCS 2022 Conference*, Beijing, China, September 2022. [Search](https://cir.nii.ac.jp/all?q=Approximate%20equation%20for%20evaluating%20global%20buckling%20load%20of%20single-layer%20cylindrical%20space%20frames%20with%20crossing%20pattern)
7. ◯ B. Liu, P.S. Chen, **J. Jin**, and X. Yan. "Approximate estimation for global buckling load of cylindrical single-layer grid shells: Fitting on envelope equations based on regression analysis." *Proceedings of the 7th International Conference on Civil Engineering (ICOCE 2023)*, Singapore, March 2023. [DOI](https://doi.org/10.1007/978-981-99-4045-5_21)
8. ◯ B. Liu, P.S. Chen, **J. Jin**, and X. Yan. "The approximate equation for global buckling load of grid shell domes." *Proceedings of the 3rd International Civil Engineering and Architecture Conference (CEAC 2023)*, Kyoto, Japan, March 2023. [DOI](https://doi.org/10.1007/978-981-99-6368-3_24)
9. ◯ B. Liu, P.S. Chen, **J. Jin**, and X. Yan. "Approximate equation for estimating global buckling load of single-layer cylindrical space frames." *Proceedings of the 10th AWAM International Conference on Civil Engineering (AICCE 2022)*, Universiti Sains Malaysia (USM), February 2022. [DOI](https://doi.org/10.1007/978-981-99-6018-7_16)
10. ◯ B. Liu, P.S. Chen, X. Yan, and **J. Jin**. "Evaluation equation on global buckling load for cylindrical single-layer and 1.5-layer space frames." *Proceedings of the 9th International Symposium on Applied Engineering and Sciences (SAES 2021)*, Universiti Putra Malaysia (UPM), p. 361, December 2021. [Search](https://cir.nii.ac.jp/all?q=Evaluation%20equation%20on%20global%20buckling%20load%20for%20cylindrical%20single-layer%20and%201.5-layer%20space%20frames)


**Japanese Conference Proceedings** (◯ Presenter)
======

1. ◯ **J. Jin**, T. Yan, T. Nagae, and Y.L. Chung. "Study on pre-earthquake retrofitting and post-earthquake repairments for beam ends in existing high-rise steel buildings, Part 1: Seismic performance assessment method for the frames with retrofitted beam ends." *Summaries of Technical Papers of Annual Meeting 2024, AIJ*, pp. 901-902, August 2024. [Search](https://cir.nii.ac.jp/all?q=Study%20on%20pre-earthquake%20retrofitting%20and%20post-earthquake%20repairments%20Part%201)
2. ◯ **J. Jin**, J. Li, T. Nagae, T. Okazaki, T. Asai, et al. "Comprehensive seismic performance assessment testing, Part 23: Seismic performance of buckling-restrained braces in 10-story steel test specimen." *Summaries of Technical Papers of Annual Meeting 2023, AIJ*, pp. 1211-1212, September 2023. [Search](https://cir.nii.ac.jp/all?q=Comprehensive%20seismic%20performance%20assessment%20testing%20Part%2023)
3. ◯ **J. Jin**, J. Li, T. Nagae, T. Okazaki, T. Asai, et al. "Data reduction for the 2023 E-Defense shaking table test on 10-story steel frame structure, Part 2: Contribution of buckling-restrained braces." *AIJ Hokkaido Chapter Architectural Research Meeting*, No. 96, pp. 53-56, June 2023. [Search](https://cir.nii.ac.jp/all?q=Data%20reduction%202023%20E-Defense%2010-story%20steel%20Part%202)
4. ◯ **J. Jin**, T. Okazaki, T. Nagae, N. Takahashi, T. Matsumiya, J. Fujiwara, A. Kishida, and K. Kajiwara. "Comprehensive seismic performance assessment testing, Part 5: Ultimate failure simulation of the ten-story test specimen." *Summaries of Technical Papers of Annual Meeting 2022, AIJ*, pp. 823-824, September 2022. [Search](https://cir.nii.ac.jp/all?q=Comprehensive%20seismic%20performance%20assessment%20testing%20Part%205)
5. ◯ **J. Jin** and P.S. Chen. "Dynamic mechanical properties of cylindrical 1.5-layer space frames with inclined lap-units." *Summaries of Technical Papers of Annual Meeting 2021, AIJ*, pp. 687-688, September 2021. [Search](https://cir.nii.ac.jp/all?q=Dynamic%20mechanical%20properties%20cylindrical%201.5-layer%20space%20frames%20inclined%20lap-units)
6. ◯ **J. Jin**, X. Qian, and P.S. Chen. "Buckling characteristics of domed 1.5-layer space frames with lap-units." *AIJ Kyushu Chapter Architectural Research Meeting*, No. 60, pp. 213-216, March 2021. [Search](https://cir.nii.ac.jp/all?q=Buckling%20characteristics%20domed%201.5-layer%20space%20frames%20lap-units)
7. ◯ **J. Jin**, X. Qian, and P.S. Chen. "Buckling characteristics of cylindrical 1.5-layer space frames with lap-units." *Summaries of Technical Papers of Annual Meeting 2020, AIJ*, pp. 751-752, September 2020. [Search](https://cir.nii.ac.jp/all?q=Buckling%20characteristics%20cylindrical%201.5-layer%20space%20frames%20lap-units)
8. ◯ Y.L. Chung, T. Yan, **J. Jin**, and T. Nagae. "Study on pre-earthquake retrofitting and post-earthquake repairments for beam ends in existing high-rise steel buildings, Part 2: FE analysis on retrofitted beam ends in E-Defense high-rise frames." *Summaries of Technical Papers of Annual Meeting 2024, AIJ*, pp. 903-904, August 2024. [Search](https://cir.nii.ac.jp/all?q=Study%20on%20pre-earthquake%20retrofitting%20and%20post-earthquake%20repairments%20Part%202)
9. ◯ E. Shigeta, **J. Jin**, T. Yan, Y.L. Chung, and T. Nagae. "Study on pre-earthquake retrofitting and post-earthquake repairments for beam ends in existing high-rise steel buildings, Part 3: Cyclic loading tests on welding repairments to bottom flange/bolted web connections at beam end." *Summaries of Technical Papers of Annual Meeting 2024, AIJ*, pp. 905-906, August 2024. [Search](https://cir.nii.ac.jp/all?q=Study%20on%20pre-earthquake%20retrofitting%20and%20post-earthquake%20repairments%20Part%203)
10. ◯ T. Yan, **J. Jin**, T. Nagae, and Y.L. Chung. "Study on pre-earthquake retrofitting and post-earthquake repairments for beam ends in existing high-rise steel buildings, Part 4: FE analysis on welding repairments to bottom flange/bolted web connections at beam end." *Summaries of Technical Papers of Annual Meeting 2024, AIJ*, pp. 907-908, August 2024. [Search](https://cir.nii.ac.jp/all?q=Study%20on%20pre-earthquake%20retrofitting%20and%20post-earthquake%20repairments%20Part%204)
11. ◯ Y. Gao, T. Nagae, **J. Jin**, C. Yenidogan, and J.D. Kang. "Review of ATC manual and numerical analysis of E-Defense 10-story RC building." *Summaries of Technical Papers of Annual Meeting 2024, AIJ*, pp. 457-458, August 2024. [Search](https://cir.nii.ac.jp/all?q=Review%20ATC%20manual%20numerical%20analysis%20E-Defense%2010-story%20RC%20building)
12. ◯ J. Li, **J. Jin**, T. Okazaki, T. Nagae, J. Fujiwara, et al. "Comprehensive seismic performance assessment testing, Part 22: Experimental response of internal panel zones, beams and columns." *Summaries of Technical Papers of Annual Meeting 2023, AIJ*, pp. 1209-1210, September 2023. [Search](https://cir.nii.ac.jp/all?q=Comprehensive%20seismic%20performance%20assessment%20testing%20Part%2022)
13. ◯ J. Li, **J. Jin**, T. Okazaki, T. Nagae, J. Fujiwara, et al. "Data reduction for the 2023 E-Defense shaking table test on 10-story steel frame structure, Part 1: Instrumentation plan and measured response of beams, panel zones and columns." *AIJ Hokkaido Chapter Architectural Research Meeting*, No. 96, pp. 49-52, June 2023. [Search](https://cir.nii.ac.jp/all?q=Data%20reduction%202023%20E-Defense%2010-story%20steel%20Part%201)
14. ◯ K. Takaya, T. Nagae, **J. Jin**, T. Asai, K. Kajiwara, et al. "Comprehensive seismic performance assessment testing, Part 18: Numerical analysis and experiments in ESDOF." *Summaries of Technical Papers of Annual Meeting 2023, AIJ*, pp. 1201-1202, September 2023. [Search](https://cir.nii.ac.jp/all?q=Comprehensive%20seismic%20performance%20assessment%20testing%20Part%2018)
15. ◯ Y. Gao, T. Nagae, **J. Jin**, K. Takaya, T. Asai, et al. "Comprehensive seismic performance assessment testing, Part 20: ESDOF system estimation for 10-story steel and RC test structures." *Summaries of Technical Papers of Annual Meeting 2023, AIJ*, pp. 1205-1206, September 2023. [Search](https://cir.nii.ac.jp/all?q=Comprehensive%20seismic%20performance%20assessment%20testing%20Part%2020)
16. ◯ Y.L. Chung, T. Nagae, **J. Jin**, D. Lignos, T. Okazaki, et al. "Comprehensive seismic performance assessment testing, Part 4: Numerical simulation of the ten-story test specimen." *Summaries of Technical Papers of Annual Meeting 2022, AIJ*, pp. 821-822, September 2022. [Search](https://cir.nii.ac.jp/all?q=Comprehensive%20seismic%20performance%20assessment%20testing%20Part%204)
17. ◯ A. Kishida, J. Fujiwara, K. Kajiwara, T. Nagae, **J. Jin**, et al. "Comprehensive seismic performance assessment testing, Part 6: Comparison of the ten-story test specimen and the prototype building." *Summaries of Technical Papers of Annual Meeting 2022, AIJ*, pp. 825-826, September 2022. [Search](https://cir.nii.ac.jp/all?q=Comprehensive%20seismic%20performance%20assessment%20testing%20Part%206)
18. ◯ B. Liu, X. Yan, P.S. Chen, and **J. Jin**. "Approximate equations for estimating global buckling load of single-layer cylindrical grid shells with crossing pattern." *Summaries of Technical Papers of Annual Meeting 2022, AIJ*, pp. 629-630, September 2022. [Search](https://cir.nii.ac.jp/all?q=Approximate%20equations%20global%20buckling%20single-layer%20cylindrical%20grid%20shells%20crossing%20pattern)
19. ◯ X. Yan, P.S. Chen, B. Liu, and **J. Jin**. "The effect of hollow body properties on the mechanical characteristics of bubble concrete: A review of bubble concrete." *Summaries of Technical Papers of Annual Meeting 2022, AIJ*, pp. 97-98, September 2022. [Search](https://cir.nii.ac.jp/all?q=effect%20hollow%20body%20properties%20mechanical%20characteristics%20bubble%20concrete)
20. ◯ B. Liu, P.S. Chen, X. Yan, and **J. Jin**. "The application of regression analysis in evaluating the buckling load for single-layer space frame." *AIJ Kyushu Chapter Architectural Research Meeting*, No. 61, pp. 261-264, March 2022. [Search](https://cir.nii.ac.jp/all?q=application%20regression%20analysis%20buckling%20load%20single-layer%20space%20frame)
21. ◯ X. Yan, **J. Jin**, and P.S. Chen. "Numerical simulation on lightweight concrete mixed with high-strength ceramic hollow body." *Summaries of Technical Papers of Annual Meeting 2021, AIJ*, pp. 91-92, September 2021. [Search](https://cir.nii.ac.jp/all?q=Numerical%20simulation%20lightweight%20concrete%20high-strength%20ceramic%20hollow%20body)
22. ◯ **金家良**, 鈴木里佳子, and 長江拓也. "10層鋼構造骨組におけるカーテンウォールセンシング技術を用いた建築耐震性能評価のための実験と解析." *2022年減災連携研究センター地域減災研究ワークショップ*, セッション3：耐震建築・免震, August 2022. [Search](https://cir.nii.ac.jp/all?q=10層鋼構造骨組におけるカーテンウォールセンシング技術を用いた建築耐震性能評価のための実験と解析)
